--[[
	Common file to store all game constants.
]]

VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

TILE_SIZE = 16

-- Entity definitions
BIRDDOG_RUN_SPEED = 60

backgroundScroll = 0
fenceScroll = 0
BACKGROUND_SCROLL_SPEED = 40
BACKGROUND_LOOPING_POINT = 414
FENCE_SCROLL_SPEED = 30